# Generated by Django 4.0.5 on 2022-06-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemonentity_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='title',
        ),
    ]
